### ISSUE TITLE
Not sure if this project is still active, but it does not run :(

### ISSUE THREAD

**Issue by rvt** [ranomier/pymumble-abot#3]
Followed all steps.
Python 3.7

`(python-for-pymumble-abot) pi@raspberrypi:~/pymumble-abot $ ./abot.py --host 127.0.0.1
Traceback (most recent call last):
  File "./abot.py", line 16, in <module>
    from thrd_party import pymumble
  File "/home/pi/pymumble-abot/thrd_party/pymumble/__init__.py", line 3, in <module>
    from .mumble import Mumble
  File "/home/pi/pymumble-abot/thrd_party/pymumble/mumble.py", line 12, in <module>
    from . import users
  File "/home/pi/pymumble-abot/thrd_party/pymumble/users.py", line 4, in <module>
    from . import soundqueue
  File "/home/pi/pymumble-abot/thrd_party/pymumble/soundqueue.py", line 6, in <module>
    import opuslib
  File "/home/pi/python-for-pymumble-abot/local/lib/python2.7/site-packages/opuslib/__init__.py", line 19, in <module>
    from .exceptions import OpusError  # NOQA
  File "/home/pi/python-for-pymumble-abot/local/lib/python2.7/site-packages/opuslib/exceptions.py", line 23
    def __init__(self, code: int) -> None:
                           ^
SyntaxError: invalid syntax`

**Comment by ranomier** [comment]
Lol, just tried it myself. recently. Sorry did not see your message. I'm not very active on github.

I will look into it
